apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-read
  labels:
    app: dummyread
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummyread
  template:
    metadata:
      labels:
        app: dummyread
    spec:
      volumes:
      - name: dummy-pv-storage
        persistentVolumeClaim:
          claimName: dummy-pv-claim
      containers:
      - name: dummyread
        image: lucassantoss/dummyread:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/app/data"
          name: dummy-pv-storage
